---
sidebar: sidebar 
permalink: configure-notifications.html 
keywords: amazon, sns, notification, topic, notifications, notifications service, alerts 
summary: 特定の種類のイベントが発生したときに、ユーザーまたは別のアプリケーションに通知を送信するように BlueXP ワークロード ファクトリーを構成できます。 
---
= BlueXPワークロードファクトリー通知を構成する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP ワークロードファクトリー通知サービスを設定して、BlueXP アラートサービスまたは Amazon SNS トピックに通知を送信できます。BlueXPアラートに送信された通知は、BlueXP アラートパネルに表示されます。ワークロードファクトリーが Amazon SNS トピックに通知を発行すると、トピックのサブスクライバー（ユーザーや他のアプリケーションなど）は、トピックに設定されたエンドポイント（E メールや SMS メッセージなど）で通知を受け取ります。



== 通知の種類とメッセージ

ワークロード ファクトリーは、次のイベントの通知を送信します。

[cols="6*"]
|===
| イベント | 製品説明 | 通知のタイプ | 重大度 | ワークロード | リソースタイプ 


| アカウント内の一部のデータベースインスタンスは適切に設計されていません | アカウント内のすべてのMicrosoft SQL Serverインスタンスについて、Well-Architectedの問題が分析されました。このイベントの説明には、Well-Architectedインスタンスと最適化されていないインスタンスの数が表示されます。ワークロードファクトリーコンソールのデータベースインベントリで、Well-Architectedステータスの調査結果と推奨事項を確認してください。 | 優れた設計 | 推奨事項 | データベース | Microsoft SQL Serverインスタンス 


| Microsoft SQL Server/PostgreSQL サーバーの展開に成功しました | Microsoft SQL Server または PostgreSQL ホストのデプロイに成功しました。詳細については、ジョブ監視を参照してください。 | 導入 | 成功 | データベース | FSx for ONTAP、DBホスト 


| Microsoft SQL Server/PostgreSQL サーバーの展開に失敗しました | Microsoft SQL Server または PostgreSQL ホストのデプロイに失敗しました。詳細については、ジョブ監視を参照してください。 | 導入 | エラー | データベース | FSx for ONTAP、DBホスト 
|===


== ワークロードファクトリー通知を構成する

BlueXPコンソールまたはワークロードファクトリーコンソールを使用して、ワークロードファクトリーの通知を設定します。BlueXPコンソールを使用する場合は、BlueXPアラートまたはAmazon SNSトピックに通知を送信するようにワークロードファクトリーを設定できます。BlueXPアラートは、BlueXPの*アラートと通知設定*領域から設定できます。

.開始する前に
* Amazon SNS コンソールまたは AWS CLI を使用して、Amazon SNS を設定し、Amazon SNS トピックを作成する必要があります。
* ワークロードファクトリーは*標準*トピックタイプをサポートしています。このタイプのトピックでは、通知が受信順にサブスクライバーに送信されるとは限りません。そのため、重要な通知や緊急の通知がある場合は、このタイプを検討してください。


[role="tabbed-block"]
====
.BlueXPコンソールから通知を設定する
--
.手順
. にログインし link:https://console.bluexp.netapp.com["BlueXPコンソール"^]ます。
. 左側のナビゲーションから*[ワークロード]*を選択します。
. [ホーム]*を選択してすべてのワークロードを表示するか、*[ストレージ]*や*[データベース]*などのワークロードを1つ選択します。
. ワークロード ファクトリーのメニュー バーから、構成メニューを選択します。
. メニューで、*Workload Factory 通知設定*を選択します。
. オプション: *BlueXP 通知を有効にする* を選択して、ワークロード ファクトリーが BlueXP アラートに通知を送信するように構成します。
. *SNS通知を有効にする*を選択します。
. Amazon SNS コンソールから Amazon SNS を設定するには、指示に従います。
+
トピックを作成したら、トピック ARN をコピーして、*通知設定*ダイアログの*SNS トピック ARN* フィールドに入力します。

. テスト通知を送信して構成を確認した後、[適用] を選択します。


.結果
ワークロードファクトリーは、指定した Amazon SNS トピックに通知を送信するように設定されています。

--
.ワークロードファクトリーコンソールから通知を構成する
--
.手順
. にログインし link:https://console.workloads.netapp.com["ワークロードファクトリコンソール"^]ます。
. 上部のナビゲーション バーからアカウント メニューを開きます。
. メニューで*通知設定*を選択します。
. *SNS通知を有効にする*を選択します。
. Amazon SNS コンソールから Amazon SNS を設定するには、指示に従います。
. テスト通知を送信して構成を確認した後、[適用] を選択します。


.結果
ワークロードファクトリーは、指定した Amazon SNS トピックに通知を送信するように設定されています。

--
====


== Amazon SNSトピックを購読する

トピックに通知を送信するようにワークロードファクトリーを構成したら、  https://docs.aws.amazon.com/sns/latest/dg/sns-create-subscribe-endpoint-to-topic.html["説明書"] Amazon SNS ドキュメントの手順に従ってトピックをサブスクライブし、ワークロードファクトリーから通知を受信できるようにします。



== 通知をフィルタリングします

通知にフィルターを適用することで、不要な通知トラフィックを削減し、特定のユーザーに特定の通知タイプを絞り込むことができます。これは、SNS通知にはAmazon SNSポリシーを使用し、BlueXP通知にはBlueXP通知設定を使用することで実現できます。



=== Amazon SNS通知をフィルタリングする

Amazon SNS トピックをサブスクライブすると、デフォルトでそのトピックに公開されたすべての通知を受信します。トピックから特定の通知のみを受信する場合は、フィルター ポリシーを使用して、受信する通知を制御できます。フィルタポリシーにより、Amazon SNS はフィルタポリシーに一致する通知のみをサブスクライバーに配信します。

Amazon SNS 通知は、次の基準でフィルタリングできます。

[cols="3*"]
|===
| 製品説明 | フィルターポリシーフィールド名 | 可能な値 


| リソースタイプ | `resourceType`  a| 
* `DB`
* `Microsoft SQL Server host`
* `PostgreSQL Server host`




| ワークロード | `workload` | `WLMDB` 


| 優先度 | `priority`  a| 
* `Success`
* `Info`
* `Recommendation`
* `Warning`
* `Error`
* `Critical`




| 通知のタイプ | `notificationType`  a| 
* `Deployment`
* `Well-architected`


|===
.手順
. Amazon SNS コンソールで、SNS トピックのサブスクリプションの詳細を編集します。
. *サブスクリプション フィルター ポリシー* 領域で、*メッセージ属性* でフィルターすることを選択します。
. *サブスクリプション フィルター ポリシー* オプションを有効にします。
. *JSON エディター* ボックスに JSON フィルター ポリシーを入力します。
+
たとえば、次の JSON フィルター ポリシーは、WLMDB ワークロードに関連し、優先度が成功またはエラーであり、Well-architected ステータスの詳細を提供する Microsoft SQL Server リソースからの通知を受け入れます。

+
[source, json]
----
{
  "accountId": [
    "account-a"
  ],
  "resourceType": [
    "Microsoft SQL Server host"
  ],
  "workload": [
    "WLMDB"
  ],
  "priority": [
    "Success",
    "Error"
  ],
  "notificationType": [
    "Well-architected"
  ]
}
----
. *変更を保存*を選択します。


その他のフィルタポリシーの例については、以下を参照してください。 https://docs.aws.amazon.com/sns/latest/dg/example-filter-policies.html["Amazon SNS のフィルターポリシーの例"^] 。

フィルタポリシーの作成の詳細については、 https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html["Amazon SNSのドキュメント"^] 。



=== BlueXP通知をフィルタリングする

BlueXP のアラートおよび通知設定を使用すると、BlueXP で受信するアラートと通知を重大度レベル (重大、情報、警告など) でフィルタリングできます。

BlueXPでの通知フィルタリングの詳細については、  https://docs.netapp.com/us-en/bluexp-setup-admin/task-monitor-cm-operations.html#filter-notifications["BlueXPのマニュアル"^] 。
