---
sidebar: sidebar 
permalink: configure-notifications.html 
keywords: amazon, sns, notification, topic, notifications, notifications service, alerts 
summary: 特定の種類のイベントが発生したときに、ユーザーまたは別のアプリケーションに通知を送信するようにNetApp Workload Factory を構成できます。 
---
= NetApp Workload Factory 通知を構成する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory 通知サービスを設定して、 NetAppコンソールまたは Amazon SNS トピックにアラートとして通知を送信できます。コンソール エージェントまたはリンクが展開されている場合、アラートとして送信された通知はNetAppコンソールに表示されます。  Workload Factory が Amazon SNS トピックに通知を発行すると、トピックのサブスクライバー (ユーザーや他のアプリケーションなど) は、トピックに設定されたエンドポイント (電子メールや SMS メッセージなど) で通知を受信します。



== 通知の種類とメッセージ

Workload Factory は次のイベントの通知を送信します。

[cols="6*"]
|===
| イベント | 製品説明 | 通知のタイプ | 重大度 | ワークロード | リソースタイプ 


| アカウント内の一部のデータベースインスタンスは適切に設計されていません | アカウント内のすべての Microsoft SQL Server インスタンスは、well-architected の問題について分析されています。このイベントの説明には、適切に設計されたインスタンスと最適化されていないインスタンスの数が表示されます。  Workload Factory コンソールから、データベース インベントリ内の well-architected ステータスの調査結果と推奨事項を確認します。 | 優れた設計 | 推奨事項 | データベース | Microsoft SQL Serverインスタンス 


| Microsoft SQL Server/PostgreSQL サーバーの展開に成功しました | Microsoft SQL Server または PostgreSQL ホストのデプロイに成功しました。詳細については、ジョブ監視を参照してください。 | 導入 | 成功 | データベース | FSx for ONTAP、DBホスト 


| Microsoft SQL Server/PostgreSQL サーバーの展開に失敗しました | Microsoft SQL Server または PostgreSQL ホストのデプロイに失敗しました。詳細については、ジョブ監視を参照してください。 | 導入 | エラー | データベース | FSx for ONTAP、DBホスト 


| レプリケーション関係の作成に失敗しました | SnapMirrorレプリケーション関係の作成に失敗しました。詳細については、Tracker をご覧ください。 | レプリケーション | 致命的 | 一般的な保管 | ONTAP向け FSx 


| FSx for ONTAP の作成失敗 | FSx for ONTAPファイル システムの作成プロセスが失敗しました。詳細については、Tracker をご覧ください。 | FSx for ONTAPファイルシステムアクション | 致命的 | 一般的な保管 | ONTAP向け FSx 


| 自動SSD容量またはinodeにより成功率が向上する | 最近の自動容量管理更新中に、FSx for ONTAPファイル システムによって SSD 容量またはボリューム inode のいずれかが正常に増加しました。詳細については、Tracker をご覧ください。 | 容量管理 | 成功 | 一般的な保管 | FSx for ONTAPファイル 


| 自動SSD容量またはinodeの障害増加 | 最近の自動容量管理更新中に、FSx for ONTAPファイル システムは SSD 容量またはボリューム inode を増やすことができませんでした。詳細については、Tracker をご覧ください。 | 容量管理 | 致命的 | 一般的な保管 | ONTAPファイルシステム用の FSx 


| FSx for ONTAP の問題が検出されました | すべての FSx for ONTAPファイル システムについて、well-architected の問題について分析されています。スキャンにより 1 つ以上の問題が検出されました。詳細については、Workload Factory コンソールのストレージ ダッシュボードの well-architected 分析を確認してください。 | 適切に設計された分析 | 推奨事項 | 一般的な保管 | ONTAPファイルシステム用の FSx 
|===


== ワークロードファクトリーの通知を構成する

NetAppコンソールまたは Workload Factory コンソールを使用して、Workload Factory 通知を構成します。  NetAppコンソールを使用する場合は、 NetAppコンソールまたは Amazon SNS トピックにアラートとして通知を送信するように Workload Factory を設定できます。  NetAppコンソールの *通知設定* から通知を設定できます。

.開始する前に
* Amazon SNS コンソールまたは AWS CLI を使用して、Amazon SNS を設定し、Amazon SNS トピックを作成する必要があります。
* Workload Factory は *Standard* トピック タイプをサポートしていることに注意してください。このタイプのトピックでは、通知が受信順にサブスクライバーに送信されるとは限りません。そのため、重要な通知や緊急の通知がある場合は、この点を考慮してください。


[role="tabbed-block"]
====
.NetAppコンソールからの通知を構成する
--
.手順
. ログインlink:https://console.netapp.com["NetAppコンソール"^]。
. NetAppコンソール メニューから、*ワークロード*、*管理*、*通知設定*の順に選択します。
. 通知設定ページで、次の操作を行います。
+
.. オプション: NetAppコンソールで通知を送信するように Workload Factory を構成するには、* NetAppコンソール通知を有効にする* を選択します。
.. *SNS通知を有効にする*を選択します。
.. Amazon SNS コンソールから Amazon SNS を設定するには、指示に従います。
+
トピックを作成したら、トピック ARN をコピーして、*通知設定*ページの *SNS トピック ARN* フィールドに入力します。



. テスト通知を送信して構成を確認した後、[適用] を選択します。


.結果
Workload Factory は、指定した Amazon SNS トピックに通知を送信するように設定されています。

--
.Workload Factory コンソールから通知を構成する
--
.手順
. ログインlink:https://console.workloads.netapp.com["ワークロードファクトリーコンソール"^]。
. Workload Factory コンソール メニューから、*ワークロード*、*管理*、*通知設定*の順に選択します。
. *SNS通知を有効にする*を選択します。
. Amazon SNS コンソールから Amazon SNS を設定するには、指示に従います。
. テスト通知を送信して構成を確認した後、[適用] を選択します。


.結果
Workload Factory は、指定した Amazon SNS トピックに通知を送信するように設定されています。

--
====


== Amazon SNSトピックを購読する

トピックに通知を送信するようにWorkload Factoryを設定したら、 https://docs.aws.amazon.com/sns/latest/dg/sns-create-subscribe-endpoint-to-topic.html["説明書"] Amazon SNS ドキュメントの手順に従ってトピックをサブスクライブし、Workload Factory から通知を受信できるようにします。



== 通知をフィルタリングします

通知にフィルターを適用することで、不要な通知トラフィックを削減し、特定のユーザーに対して特定の通知タイプをターゲットにすることができます。これは、SNS 通知用の Amazon SNS ポリシーと、 NetAppコンソールの通知設定を使用して実行できます。



=== Amazon SNS通知をフィルタリングする

Amazon SNS トピックをサブスクライブすると、デフォルトでそのトピックに公開されたすべての通知を受信します。トピックから特定の通知のみを受信する場合は、フィルター ポリシーを使用して、受信する通知を制御できます。フィルタポリシーにより、Amazon SNS はフィルタポリシーに一致する通知のみをサブスクライバーに配信します。

Amazon SNS 通知は、次の基準でフィルタリングできます。

[cols="3*"]
|===
| 製品説明 | フィルターポリシーフィールド名 | 可能な値 


| リソースタイプ | `resourceType`  a| 
* `DB`
* `Microsoft SQL Server host`
* `PostgreSQL Server host`




| ワークロード | `workload` | `WLMDB` 


| 優先度 | `priority`  a| 
* `Success`
* `Info`
* `Recommendation`
* `Warning`
* `Error`
* `Critical`




| 通知のタイプ | `notificationType`  a| 
* `Deployment`
* `Well-architected`


|===
.手順
. Amazon SNS コンソールで、SNS トピックのサブスクリプションの詳細を編集します。
. *サブスクリプション フィルター ポリシー* 領域で、*メッセージ属性* でフィルターすることを選択します。
. *サブスクリプション フィルター ポリシー* オプションを有効にします。
. *JSON エディター* ボックスに JSON フィルター ポリシーを入力します。
+
たとえば、次の JSON フィルター ポリシーは、WLMDB ワークロードに関連し、優先度が成功またはエラーであり、Well-architected ステータスの詳細を提供する Microsoft SQL Server リソースからの通知を受け入れます。

+
[source, json]
----
{
  "accountId": [
    "account-a"
  ],
  "resourceType": [
    "Microsoft SQL Server host"
  ],
  "workload": [
    "WLMDB"
  ],
  "priority": [
    "Success",
    "Error"
  ],
  "notificationType": [
    "Well-architected"
  ]
}
----
. *変更を保存*を選択します。


その他のフィルタポリシーの例については、以下を参照してください。 https://docs.aws.amazon.com/sns/latest/dg/example-filter-policies.html["Amazon SNS のフィルターポリシーの例"^] 。

フィルタポリシーの作成の詳細については、 https://docs.aws.amazon.com/sns/latest/dg/sns-message-filtering.html["Amazon SNSのドキュメント"^] 。



=== NetAppコンソールで通知をフィルタリングする

NetAppコンソールの通知設定を使用すると、コンソールで受信する通知を重大度レベル (重大、情報、警告など) でフィルタリングできます。

コンソールでの通知のフィルタリングの詳細については、 https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#filter-notifications["NetAppコンソールのドキュメント"^] 。
