---
sidebar: sidebar 
permalink: console-experiences.html 
keywords: console, consoles, access, saas, Workload Factory, NetApp Workload Factory, NetApp Console 
summary: NetApp Workload Factory には、2 つの Web ベースのコンソールからアクセスできます。 
---
= コンソールエクスペリエンス
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory には、2 つの Web ベースのコンソールからアクセスできます。  Workload Factory コンソールとNetAppコンソールを使用して Workload Factory にアクセスする方法を学習します。

* * NetAppコンソール*: FSx for ONTAPファイルシステムとAmazon FSx for NetApp ONTAPで実行されているワークロードを同じ場所で管理できるハイブリッドエクスペリエンスを提供します。
* *Workload Factory コンソール*: Amazon FSx for NetApp ONTAPで実行されるワークロードに重点を置いた専用の Workload Factory エクスペリエンスを提供します。




== NetAppコンソールでワークロードファクトリーにアクセスする

NetApp Consoleから Workload Factory にアクセスできます。Workload Factory を AWS ストレージおよびワークロード機能に使用することに加えて、 NetApp Copy and Syncなどの他のデータ サービスにもアクセスすることができます。

.手順
. ログインlink:https://console.netapp.com["NetAppコンソール"^]。
. NetAppコンソール メニューから、*ワークロード* を選択し、次に *概要* を選択します。




== Workload FactoryコンソールでWorkload Factoryにアクセスします

Workload Factory コンソールから Workload Factory にアクセスできます。

.ステップ
. ログインlink:https://console.workloads.netapp.com["ワークロードファクトリーコンソール"^]。

