---
sidebar: sidebar 
permalink: log-in.html 
keywords: logging in, log in, sign in, signing in, user account, login with netapp, log in with netapp, sign up, create account 
summary: ワークロードファクトリにサインアップすると、Webベースのコンソールからいつでもログインして、ワークロードとFSx for ONTAPファイルシステムの管理を開始できます。 
---
= BlueXP  ワークロードファクトリにログイン
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  ワークロードファクトリにサインアップすると、Webベースのコンソールからいつでもログインして、ワークロードとFSx for ONTAPファイルシステムの管理を開始できます。

.タスクの内容
次のいずれかのオプションを使用して、Workload FactoryのWebベースコンソールにログインできます。

* 既存のNetApp Support Site （NSS）のクレデンシャルを必要に応じて変更
* Eメールアドレスとパスワードを使用したネットアップクラウドへのログイン


.手順
. Webブラウザを開き、に移動します https://console.workloads.netapp.com["ワークロードファクトリコンソール"^]。
. [ログイン*]ページで、ログインに関連付けられている電子メールアドレスを入力します。
. ログインに関連付けられている認証方法に応じて、クレデンシャルの入力を求められます。
+
** ネットアップクラウドクレデンシャル：パスワードを入力します
** フェデレーテッドユーザ：フェデレーテッドアイデンティティクレデンシャルを入力します
** NetApp Support Site アカウント：NetApp Support Site クレデンシャルを入力します


. [ログイン]*を選択します。
+
過去に正常にログインした場合は、ワークロードファクトリのホームページが表示され、デフォルトのアカウントを使用します。

+
初めてログインする場合は、*アカウント*ページが表示されます。

+
** 1つのアカウントのメンバーである場合は、*続行*を選択します。
** 複数のアカウントのメンバーである場合は、アカウントを選択して*続行*を選択します。




.結果
これでログインが完了し、ワークロードファクトリを使用してFSx for ONTAPファイルシステムとワークロードを管理できるようになります。
