---
sidebar: sidebar 
permalink: manage-custom-dashboards.html 
keywords: manage dashboards, edit dashboard, delete dashboard, refresh dashboard, dashboard catalog 
summary: Workload Factory のダッシュボードカタログにアクセスして、カスタムダッシュボードの表示、編集、更新、削除を行います。 
---
= カスタムダッシュボードを管理する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ダッシュボードカタログからカスタムダッシュボードを管理できます。そこから、詳細の表示、データの更新、ダッシュボード設定の編集、不要になったダッシュボードの削除を行うことができます。

.タスクの内容
Workload Factoryアカウントのすべてのユーザーは、すべてのカスタムダッシュボードにアクセスできます。各ダッシュボードには、作成者名、作成日、現在誰かが編集しているかどうかといった基本的な詳細情報が表示されます。

カスタムダッシュボードは読み取り専用です。ストレージやワークロードの設定を変更することはできません。ダッシュボード自体は編集できますが、監視対象のリソースは編集できません。

.開始する前に
Workload Factoryアカウントには、少なくとも1つのカスタムダッシュボードが必要です。



== ダッシュボードカタログにアクセスする

.手順
. いずれかを使用してログインしlink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["コンソールエクスペリエンス"^]ます。
. メニューから「Workloads Overview」を選択し、次に「Custom dashboards」を選択します。
+
ダッシュボードカタログには、Workload Factoryアカウント内のすべてのカスタムダッシュボードが表示されます。

. ダッシュボードのリストを確認してください。




== ダッシュボードのデータを更新する

ダッシュボードを開くと、ダッシュボードのデータが読み込まれます。最新の情報を確認するには、更新してください。

ダッシュボードはワークロードからデータを再読み込みします。最終更新時刻は、データが更新された日時を示すように変更されます。



== ダッシュボードを編集する

ダッシュボードを編集することで、表示する指標やグラフなど、内容を変更できます。

.手順
. 「カスタムダッシュボード」ページで、編集するダッシュボードを見つけます。
. そのダッシュボードの *Actions* メニューから *Edit dashboard* を選択します。
+
他のユーザーがダッシュボードを編集している場合は、「現在、[ユーザー名]によって編集中です」などのメッセージが表示されます。相手が作業を終えるまでお待ちいただくか、相手と調整してください。

. AIとの対話の中で、変更したい内容を説明してください。
+
このプロセスは、新しいダッシュボードを作成するのと似ています。ダッシュボードが追跡するワークロード、指標、または期間を変更できます。

. 変更内容を確認し、**保存**を選択してください。


.結果
ダッシュボードは変更内容に合わせて更新されます。最終更新日も更新されます。



== ダッシュボードを削除する

不要になったダッシュボードは削除してください。この操作は永続的なものであり、元に戻すことはできません。

.手順
. 「カスタムダッシュボード」ページで、削除するダッシュボードを見つけます。
. そのダッシュボードの *Actions* ドロップダウンメニューから *Delete* を選択します。
. 削除を確認します。


.結果
ダッシュボードはWorkload Factoryアカウントから完全に削除され、すべてのユーザーがアクセスできなくなります。



== 関連情報

* link:create-custom-dashboard.html["追加のカスタムダッシュボードを作成する"]
* link:troubleshoot-custom-dashboards.html["カスタムダッシュボードのトラブルシューティング"]

