---
sidebar: sidebar 
permalink: well-architected-workloads.html 
keywords: well-architected, best practices, well-architected file system, Amazon FSx for NetApp ONTAP, FSx for ONTAP 
summary: Workload Factory は、信頼性、セキュリティ、運用の卓越性、コストの最適化、パフォーマンス効率についてワークロード構成をスキャンし、運用の卓越性を実現するための洞察と推奨事項を提供します。 
---
= NetApp Workload Factoryで適切に設計されたワークロードを構築および運用
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory、Amazon FSx for NetApp ONTAP向けのNetApp管理スイートは、AWS Well-Architected Frameworkに準拠した、信頼性が高く、安全で、効率的、かつ対費用効果の高いワークロード構成の維持と運用を支援します。Workload Factoryは、ワークロードの日常的な分析、推奨事項、および自動修正機能を提供し、健全なワークロード運用を促進します。このプロセスを自動化することで、Workload Factoryは人的ミスを最小限に抑え、ワークロード管理の一貫性を確保します。



== 仕組み

Workload Factory は、Amazon FSx for NetApp ONTAP ファイルシステムの導入環境で実行されているワークロードを毎日分析します。この分析により、適切に設計された状態、インサイト、および推奨事項が提供されます。

毎日の分析が完了すると、デプロイメントの Well-architected ダッシュボードに構成が「最適化済み」または「最適化されていない」として表示されます。全体的な最適化スコア、カテゴリ別の構成の問題、構成の問題と推奨事項のリストが表示されます。構成の問題に関する推奨事項を確認できます。一部の問題は Workload Factory によって自動的に修正できますが、その他の問題は手動での介入が必要です。この場合、Workload Factory は、推奨される変更を実装するのに役立つ詳細な手順を提供します。

ご使用の環境に適用されない構成の分析を無視することができます。これにより、不要なアラートや不正確な最適化結果を回避できます。特定の構成分析を無視すると、Workload Factory ではその構成が全体の最適化スコアに含められません。



== なぜそれが重要なのか

Workload Factoryは、継続的な評価と推奨事項、および修復策を組み合わせることで、大規模なストレージ、データベース、およびVMware環境にベストプラクティスを適用します。Workload Factoryコンソールで適用される自動修正により、人的ミスが削減され、統一された管理が確保され、ワークロードインフラストラクチャ全体でパフォーマンスと信頼性が維持されます。



== Workload Factory を使用してワークロードの設定ミスを検出して修正する

Workload Factoryを使い始めるには、サインアップして認証情報を追加し、接続を確立してAWSリソースを管理し、Amazon FSx for NetApp ONTAPを使用してワークロードを最適化します。

link:https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["クイックスタート"]



== 関連情報

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["ONTAPファイルシステム向けに適切に設計された FSx を実装する"^]
* link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["適切に設計されたデータベースワークロードを実装する"^]
* link:https://docs.netapp.com/us-en/workload-vmware/view-evs-well-architected.html["適切に設計されたEVS構成を実装する"^]

