---
sidebar: sidebar 
permalink: whats-next.html 
keywords: what you can do 
summary: ログインしてNetApp Workload Factory を設定すると、FSx for ONTAPファイルシステムを作成および管理し、その他の Workload Factory 機能を使用できるようになります。 
---
= NetApp Workload Factoryでワークロードを最適化
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ログインしてNetApp Workload Factory をセットアップしたら、 Amazon FSx for ONTAPファイルシステムの作成、FSx for ONTAP ファイルシステムへのデータベースのデプロイ、FSx for ONTAPファイルシステムを外部データストアとして使用して仮想マシン構成を VMware Cloud on AWS に移行するなど、いくつかのONTAP Factory 機能を使い始めることができます。

* https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["NetApp ONTAP 対応の Amazon FSX"^]
+
FSx for ONTAPをストレージインフラとして使用することで、現在のデータ資産を評価して分析し、コスト削減の可能性を探ります。また、ベストプラクティスに基づいてFSx for ONTAP環境をプロビジョニングしてテンプレート化し、高度な管理機能を利用できます。

* https://docs.netapp.com/us-en/workload-databases/index.html["データベースワークロード"^]
+
AWS上の既存のデータベース資産の検出、FSx for ONTAPへの移行によるコスト削減の可能性の評価、最適化のためのベストプラクティスが組み込まれたエンドツーエンドのデータベース導入、CI / CDパイプライン向けのシンクローニングの自動化が可能です。

* https://docs.netapp.com/us-en/workload-genai/index.html["玄愛"^]
+
Retrieval-Augmented Generation（RAG）インフラを導入、管理して、AIアプリケーションの精度と独自性を向上させます。データのセキュリティとコンプライアンスが組み込まれたFSx for ONTAPに関するRAGナレッジベースを作成できます。

* https://docs.netapp.com/us-en/workload-vmware/index.html["VMwareワークロード"^]
+
スマートな推奨事項と自動修正により、移行と運用を合理化できます。効率的なバックアップと堅牢なディザスタリカバリを導入VMの監視とトラブルシューティング

* https://docs.netapp.com/us-en/workload-builders/index.html["ビルダーのワークロード"^]
+
バージョン管理システムおよび CI/CD フローとのインスタント クローン統合を有効にすることで、ソフトウェア バージョンの使用とアクセスを簡素化し、時間とリソースを節約します。


