---
sidebar: sidebar 
permalink: whats-next.html 
keywords: what you can do 
summary: これでログインしてワークロードファクトリのセットアップが完了しました。FSx for ONTAPファイルシステムを作成、管理したり、他のワークロードファクトリ機能を使用したりできます。 
---
= BlueXP  Workload Factoryで次にできること
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  Workload Factoryへのログインとセットアップが完了したら、Amazon FSx for ONTAPファイルシステムの作成、FSx for ONTAPファイルシステムへのデータベースの導入、FSx for ONTAPファイルシステムを外部データストアとして使用したVMware Cloud on AWSへの仮想マシン構成の移行など、いくつかのワークロードファクトリ機能の使用を開始できます。

* https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["NetApp ONTAP 対応の Amazon FSX"^]
+
FSx for ONTAPをストレージインフラとして使用することで、現在のデータ資産を評価して分析し、コスト削減の可能性を探ります。また、ベストプラクティスに基づいてFSx for ONTAP環境をプロビジョニングしてテンプレート化し、高度な管理機能を利用できます。

* https://docs.netapp.com/us-en/workload-genai/index.html["玄愛"^]
+
Retrieval-Augmented Generation（RAG）インフラを導入、管理して、AIアプリケーションの精度と独自性を向上させます。データのセキュリティとコンプライアンスが組み込まれたFSx for ONTAPに関するRAGナレッジベースを作成できます。

* https://docs.netapp.com/us-en/workload-databases/index.html["データベースワークロード"^]
+
AWS上の既存のデータベース資産の検出、FSx for ONTAPへの移行によるコスト削減の可能性の評価、最適化のためのベストプラクティスが組み込まれたエンドツーエンドのデータベース導入、CI / CDパイプライン向けのシンクローニングの自動化が可能です。

* https://docs.netapp.com/us-en/workload-vmware/index.html["VMwareワークロード"^]
+
スマートな推奨事項と自動修正により、移行と運用を合理化できます。効率的なバックアップと堅牢なディザスタリカバリを導入VMの監視とトラブルシューティング


